build_env:
  docker:
    assumed_iam_role_arn: null
    base_image: public.ecr.aws/qwak-us-east-1/qwak-base:0.0.13-gpu
    cache: true
    env_vars:
      - HUGGINGFACE_ACCESS_TOKEN=
      - COMET_API_KEY=
      - COMET_WORKSPACE=
      - COMET_PROJECT_NAME=selfai
    no_cache: false
    params: []
    push: true

  python_env:
    dependency_file_path: requirements.txt
    git_credentials: null
    git_credentials_secret: null
    poetry: null
    virtualenv: null

  remote:
    is_remote: true
    resources:
      cpus: null
      gpu_amount: null
      gpu_type: null
      instance: gpu.a10.2xl
      memory: null

build_properties:
  branch: .
  build_id: null
  gpu_compatible: false
  model_id: selfai
  tags: []
  model_uri:
    dependency_required_folder: []
    git_branch: master
    git_credentials: null
    git_credentials_secret: null
    git_secret_ssh: null
    main_dir: .
    uri: .

deploy: false
deployment_instance: null
post_build: null
pre_build: null
purchase_option: null

steps:
  tests: true
  validate_build_artifact: true
  validate_build_artifact_timeout: 120

verbose: 0
