name: Bytewax
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "deploying"

jobs:
  build:
    name: Build Docker and Push to Ecr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create ECR Repository if not exists
        run: |
          aws ecr describe-repositories --repository-names bytewax || aws ecr create-repository --repository-name bytewax

      - name: Build Images & Push to ECR
        id: build-image
        uses: docker/build-push-action@v4
        with:
          context: ./feature-processing
          file: ./feature-processing/Dockerfile.bytewax
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/bytewax:latest
