name: inference
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "deploying"

jobs:
  build:
    name: Build Docker and Push to Ecr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Create ECR Repository if not exists
        run: |
          aws ecr describe-repositories --repository-names inference || aws ecr create-repository --repository-name inference

      - name: Build Images & Push to ECR
        id: build-image
        uses: docker/build-push-action@v4
        with:
          context: ./inference
          file: ./inference/Dockerfile.inference
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/inference:latest

  # deploy:
  #   name: Deploy inference
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: AWS - Credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{secrets.AWS_REGION}}

  #     - name: Deploy Lamda image
  #       id: deploy-lambda
  #       run: |
  #         echo "update lamda with new image version $ECR_REPOSITORY"/inference:$PROJECT_VERSION..."
  #         aws lambda update-function-code \
  #         --function-name "arn:aws:lambda:$AWS_REGION:$AWS_ACCOUNT_ID:function:inference" \
  #         --image-uri $ECR_REPOSITORY"/inference:$PROJECT_VERSION"
  #         echo "update lamda with new image version $ECR_REPOSITORY"/inference:latest..."
  #       env:
  #         AWS_REGION: ${{ secrets.AWS_REGION }}
  #         ECR_REPOSITORY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  #         PROJECT_VERSION: ${{ github.sha }}
  #         AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
