# name: Pulumi

# on:
#   workflow_dispatch:
#     inputs:
#       logLevel:
#         description: "Log level"
#         required: true
#         default: "warning"
#       tags:
#         description: "deploying"

# jobs:
#   up:
#     name: up
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-region: ${{ secrets.AWS_REGION }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#       - name: Install Poetry
#         run: |
#           python -m pip install --upgrade pip
#           pip install poetry==1.8.0
#       - uses: pulumi/actions@v6
#         with:
#           command: up
#           stack-name: dewasahu2003/selfai/dev
#           work-dir: ./ops
#         env:
#           PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
